# Generated by Django 2.0.7 on 2019-01-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Text',
            new_name='article_text',
        ),
    ]
