# Generated by Django 2.0.7 on 2019-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190109_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
